services:
  - type: web
    name: unibuddy-client
    runtime: node
    region: singapore
    plan: free

    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_WEBSOCKET_URL
        value: https://unibuddy.onrender.com
      - key: NEXT_PUBLIC_VAPID_PUBLIC_KEY
        sync: false
      - key: PORT
        value: "3001"
